---
- name: Installing APP SETUP
  hosts: app
  become: true

  tasks:
    - name: Install Python
      yum:
        name: python3
        state: latest
    - name: Python Libraries
      shell: sudo pip3 install -r /tmp/app/requirements.txt
    - name: Export Flask Variables 
      shell: "{{ item }}"
      args:
        chdir: /tmp/app/
      with_items:
      - "export FLASK_APP=app"
      - "export FLASK_ENV=development"
    # - name: Run Flask App
    #   shell: flask run --host=0.0.0.0 -p 5002
    #   become_user: vagrant
    #   args:
    #     chdir: /tmp/app/
    #   register: out
    # - debug: 
    #     msg: "{{ out }}"     
